http://localhost:4000/

###
http://localhost:4000/status

###
http://localhost:4000/blocks

###
POST http://localhost:4000/blocks

###
http://localhost:4000/balance/dc6a2c9a6a3b575667b6ca909f461b9812ccd68743baab71ca00bfd0dddf69acbb7c174f3ba2d7b1a5c620e51f995f7112bcb11e2ead117770374dfca8a5cec5

###
POST http://localhost:4000/transactions

{
    "to":"sukyung", 
    "amount":35
}

###
http://localhost:4000/mempool

###
http://localhost:4000/wallet

###
POST http://localhost:4000/peers

{
    "address": "127.0.0.1", 
    "port": "3000"
}

###
http://localhost:3000/peers